language: java
sudo: false
install: true

addons:
  sonarqube:
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - $TRAVIS_BUILD_DIR/build.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false

before_install:
 - chmod +x $TRAVIS_BUILD_DIR/build.sh
