language: java
sudo: false
install: true

addons:
  sonarqube:
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - $TRAVIS_BUILD_DIR/build.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false

before_install:
 - chmod +x $TRAVIS_BUILD_DIR/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
